# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'example'
            MYSQL_DATABASE: 'mt-route-db'
        volumes:
            - 'mysql:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
volumes:
    mysql:
        driver: local
