region: ap-northeast-1
cluster: mtroute-prod-mtroute
service: mtroute-prod-mtroute
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://mt-route-tfstate/mtroute/prod/cicd/app_mtroute_v1.0.0.tfstate
